Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Max: 40
Metrics/BlockLength:
  Max: 80

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: true
