AllCops:
  Exclude:
    - 'Rakefile'

Metrics/BlockLength:
  Max: 80
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 40

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: true
